In [163]:
import pandas as pd

In [222]:
#importing the csv into a dataframe, vivendo_claims, making note of existing index
vivendo_claims = pd.read_csv('food_claims_2212.csv', index_col=0)

#checking the output
print(vivendo_claims.head(20))
print(vivendo_claims.info())

#note: missing values in amount_paid and linked cases
#note: claim_amount not numeric type
#note: linked_cases not boolean type

          time_to_close claim_amount  amount_paid   location  \
claim_id
1                   317  R$ 74474.55     51231.37     RECIFE
2                   195  R$ 52137.83     42111.30  FORTALEZA
3                   183   R$ 24447.2     23986.30   SAO LUIS
4                   186  R$ 29006.28     27942.72  FORTALEZA
5                   138   R$ 19520.6     16251.06     RECIFE
6                   183  R$ 47529.14     38011.98      NATAL
7                   190  R$ 39073.26     29826.04   SAO LUIS
8                   183  R$ 29870.56     29727.52   SAO LUIS
9                   149  R$ 26644.46     23362.14     RECIFE
10                  149  R$ 11544.68      9680.82      NATAL
11                  180   R$ 31002.6     27110.18   SAO LUIS
12                  208  R$ 29802.86     26505.06   SAO LUIS
13                  175  R$ 23831.65     17145.09   SAO LUIS
14                  223  R$ 42626.53     31053.01     RECIFE
15                  265  R$ 36210.84     24847.68      NATAL
16                  235  R$ 47684.68     33591.00      NATAL
17                  229  R$ 40630.59     29160.14     RECIFE
18                  189  R$ 36757.41     30501.00  FORTALEZA
19                  195  R$ 10269.56      9160.26   SAO LUIS
20                  204  R$ 24765.33     19404.41     RECIFE

          individuals_on_claim linked_cases      cause
claim_id
1                           15        False    unknown
2                           12         True    unknown
3                           10         True       meat
4                           11        False       meat
5                           11        False  vegetable
6                           11        False    unknown
7                           12        False       meat
8                            8         True    unknown
9                            9        False       meat
10                           6        False  vegetable
11                           8        False    unknown
12                           8        False    unknown
13                           7        False       meat
14                          12        False       meat
15                          10        False       meat
16                          13        False       meat
17                           8        False    unknown
18                          12        False       meat
19                           4        False       meat
20                           8        False       meat
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000 entries, 1 to 2000
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time_to_close         2000 non-null   int64
 1   claim_amount          2000 non-null   object
 2   amount_paid           1964 non-null   float64
 3   location              2000 non-null   object
 4   individuals_on_claim  2000 non-null   int64
 5   linked_cases          1974 non-null   object
 6   cause                 2000 non-null   object
dtypes: float64(1), int64(2), object(4)
memory usage: 125.0+ KB
None

In [223]:
                    # time_to_close - no null values,

negative_vals_time = 0

for index, row in vivendo_claims.iterrows():
    if row["time_to_close"] < 0:
        negative_vals_time += 1
        
print('time_to_close negative vaules : ' + str(negative_vals_time))


                    # claim_amount- no null values, 'R$' removed from all rows, column type changed to float


vivendo_claims['claim_amount']=vivendo_claims['claim_amount'].apply(lambda x: x.strip('R$'))
vivendo_claims['claim_amount']=vivendo_claims['claim_amount'].astype(float)

for index, row in vivendo_claims.iterrows():
    if row["claim_amount"] < 0:
        negative_vals_claim_amount += 1

print('claim_amount negative values: ' + str(negative_vals_claim_amount))




                    #amount_paid - 36 null values replaced with median value.

null_vals_amount_paid = 0
negative_vals_amount_paid = 0
median = vivendo_claims['amount_paid'].median()

for index, row in vivendo_claims.iterrows():
    if pd.isnull(row["amount_paid"]) == True:
        null_vals_amount_paid += 1
    if row["amount_paid"] < 0:
        negative_vals_amount_paid += 1
        
print('amount paid null values: ' + str(null_vals_amount_paid))
print('value to replace null values: ' + str(median))
print('amount paid negative values: ' + str(negative_vals_amount_paid))

        
vivendo_claims['amount_paid'] = vivendo_claims['amount_paid'].fillna(value=median, inplace=False)



                # location - no null values, extra values or nonuniform formats detected
null_vals_location = 0
nonuniform_values_location = 0

for index, row in vivendo_claims.iterrows():
    if row['location'] not in ['RECIFE','NATAL','SAO LUIS','FORTALEZA']:
        nonuniform_values_location += 1
        print(row['location'])

print('location values not formatted properly: ' +str(nonuniform_values_location))



               # individuals_on_claim - no null values or other concerns. All values between 1 and 15
negative_vals_individuals = 0

for index, row in vivendo_claims.iterrows():
    if row["amount_paid"] < 0:
        negative_vals_individuals += 1
        
print(negative_vals_individuals)

print('largest number of individuals on a claim: '+ str(max(vivendo_claims['individuals_on_claim'])))
print('smallest number of individuals on a claim: '+ str(min(vivendo_claims['individuals_on_claim'])))



                # linked_cases - 26 null values which were replaced with False, column type changed to bool
null_vals_linked_cases = 0

for index, row in vivendo_claims.iterrows():
    if pd.isnull(row["linked_cases"]) == True:
        null_vals_linked_cases += 1
        
print('linked cases null values: '+ str(null_vals_linked_cases))
print('amount to replace nulls: False')

vivendo_claims['linked_cases'] = vivendo_claims['linked_cases'].fillna(value=False, inplace=False)
vivendo_claims['linked_cases']= vivendo_claims['linked_cases'].astype(bool)




                # cause - 0 null values, 30 values formatted incorrectly, updated to lowercase
wrong_format_cause = 0

for index, row in vivendo_claims.iterrows():
    if row['cause'] not in ['unknown','vegetable','meat']:
        wrong_format_cause += 1

print('cause values not formatted properly: ' +str(wrong_format_cause))

vivendo_claims['cause'] = vivendo_claims['cause'].apply(lambda x: x.lower())

time_to_close negative vaules : 0
claim_amount negative values: 0
amount paid null values: 36
value to replace null values: 20105.699999999997
amount paid negative values: 0
location values not formatted properly: 0
0
largest number of individuals on a claim: 15
smallest number of individuals on a claim: 1
linked cases null values: 26
amount to replace nulls: False
cause values not formatted properly: 30

In [221]:
print(vivendo_claims.head(20))
print(vivendo_claims.info())

#note: all columns are complete (2000 entries)
#note: claim_amount float type
#note: linked_cases boolean type

          time_to_close  claim_amount  amount_paid   location  \
claim_id
1                   317      74474.55     51231.37     RECIFE
2                   195      52137.83     42111.30  FORTALEZA
3                   183      24447.20     23986.30   SAO LUIS
4                   186      29006.28     27942.72  FORTALEZA
5                   138      19520.60     16251.06     RECIFE
6                   183      47529.14     38011.98      NATAL
7                   190      39073.26     29826.04   SAO LUIS
8                   183      29870.56     29727.52   SAO LUIS
9                   149      26644.46     23362.14     RECIFE
10                  149      11544.68      9680.82      NATAL
11                  180      31002.60     27110.18   SAO LUIS
12                  208      29802.86     26505.06   SAO LUIS
13                  175      23831.65     17145.09   SAO LUIS
14                  223      42626.53     31053.01     RECIFE
15                  265      36210.84     24847.68      NATAL
16                  235      47684.68     33591.00      NATAL
17                  229      40630.59     29160.14     RECIFE
18                  189      36757.41     30501.00  FORTALEZA
19                  195      10269.56      9160.26   SAO LUIS
20                  204      24765.33     19404.41     RECIFE

          individuals_on_claim  linked_cases      cause
claim_id
1                           15         False    unknown
2                           12          True    unknown
3                           10          True       meat
4                           11         False       meat
5                           11         False  vegetable
6                           11         False    unknown
7                           12         False       meat
8                            8          True    unknown
9                            9         False       meat
10                           6         False  vegetable
11                           8         False    unknown
12                           8         False    unknown
13                           7         False       meat
14                          12         False       meat
15                          10         False       meat
16                          13         False       meat
17                           8         False    unknown
18                          12         False       meat
19                           4         False       meat
20                           8         False       meat
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000 entries, 1 to 2000
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time_to_close         2000 non-null   int64
 1   claim_amount          2000 non-null   float64
 2   amount_paid           2000 non-null   float64
 3   location              2000 non-null   object
 4   individuals_on_claim  2000 non-null   int64
 5   linked_cases          2000 non-null   bool
 6   cause                 2000 non-null   object
dtypes: bool(1), float64(2), int64(2), object(2)
memory usage: 111.3+ KB
None